pipeline {
    agent any
    environment {
        RELEASE='20.04'
    }
    stages {
        stage('Pre-build'){
            agent any
            steps {
                echo "checking software version"
                sh '''
                python -V
                '''
                 
            }

        }

        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing. I can see release ${RELEASE} "
            }
        }

    }
}